### PR TITLE
fix/15

### PR DESCRIPTION
**Pull request by Omer975**
Text corrected in 26th line. There are no changes needed. The requested change has been cancelled. Codes were reinstated.

### CODE REVIEW

**Comment by marcopeg** [comment]
There is no description regarding how to test this, can you improve the description of the PR?

**Comment by marcopeg** [comment]
There is still no description in the PR... Plus, you should name some reviewers to take a look at this as well.

**Comment by Omer975** [comment]
Text corrected in 26th line. There are no changes needed. The requested change has been cancelled. Codes were reinstated.

**Comment by marcopeg** [comment]
mmm so we can close this PR?

**Pull request closed without merging**
